[cubi.metadata]
pid = "https://github.com/core-unit-bioinformatics/template-metadata-files"
version = "1.7.0"

[cubi.metadata.naming.workflow.system]
smk="snakemake"
nxf="nextflow"
cwl="common-workflow-language"
wdl="workflow-definition-language"

[cubi.metadata.naming.project.type]
deprecated = true
comment = "Project type is a deprecated attribute as of 2025"
dev="development"
run="production-run"
bmk="benchmark"
