[cubi.metadata]
pid = "undefined"
version = "1.3.0"

[cubi.metadata.naming.workflow.system]
smk="snakemake"
nxf="nextflow"
cwl="common-workflow-language"
wdl="workflow-definition-language"

[cubi.metadata.naming.project.type]
dev="development"
run="production-run"
bmk="benchmark"
