[cubi.workflow]
pid = "undefined"
name = "undefined"
version = "prototype"

[cubi.workflow.template]
pid = "undefined"
system = "system"
version = "prototype"

[cubi.workflow.upstream]
pid = "undefined"  
name = "undefined"
version = "prototype"